### PR TITLE
Remove cni interface annotation as part of uninstall command

### LINKED ISSUE #1728: nodes annotations added by Submariner are not deleted after Submariner uninstalled
**What happened**:
Nodes annotations added by Submariner are not deleted after Submariner is uninstalled.
Although it should not have a negative effect, it is preferable to delete it and leave no trace of Submariner after uninstallation

**What you expected to happen**:
Nodes annotations added by Submariner should be deleted
**How to reproduce it (as minimally and precisely as possible)**:
Check nodes annotations on cluster2
Run Submariner deployment
- bin/subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1
-  bin/subctl join --kubeconfig output/kubeconfigs/kind-config-cluster1  broker-info.subm --clusterid cluster1  --natt=false
-  bin/subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2  broker-info.subm --clusterid cluster2  --natt=false 

Uninstall Submariner from cluster2 
-  bin/subctl uninstall  --kubeconfig output/kubeconfigs/kind-config-cluster2

Check node annotations on cluster2

$ kubectl get nodes cluster2-control-plane -o yaml | grep annotations -A 5
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    submariner.io/cniIfaceIp: 10.2.0.1
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-03-08T23:13:06Z"
$ 

**Environment**:
Kind reswan

### PR DESCRIPTION
**Pull request by yboaron**
Submariner Route-agent annotates the cni interface IP in node resource.
This PR ensures that the cni interface IP annotation is deleted as
part of Submariner uninstallation.

Fixes: https://github.com/submariner-io/submariner/issues/1728
Signed-off-by: yboaron <yboaron@redhat.com>

### CODE REVIEW

File: pkg/routeagent_driver/cni/cni_iface.go [hunk 1]
```diff
@@ -86,9 +86,20 @@ func discover(clusterCIDR string) (*Interface, error) {
...
+	setAnnotation := true
+
+	if len(clusterCidr) == 0 {
+		setAnnotation = false
+	}
+
+	if setAnnotation {
+		cniIface, err := Discover(clusterCidr[0])
+		if err != nil {
+			return errors.Wrap(err, "Discover returned error")
```
Comment (skitt) [inline pkg/routeagent_driver/cni/cni_iface.go]: I would suggest an error such as "error retrieving the CNI interface for %s: %v", clusterCidr[0], err instead.

**Review by skitt — CHANGES_REQUESTED** [review]

**Review by skitt — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Comment by sridhargaddam** [comment]
Backported to release-0.12 branch via https://github.com/submariner-io/submariner/pull/1934
