### PR TITLE
Delete IP rules as part of uninstall flow

### LINKED ISSUE #1913: IP rule list/tables not deleted on GW node after submariner uninstall
**What happened**:
IP rule list and tables (100 and 150) were not deleted on GW node after Submariner uninstall

**What you expected to happen**:
IP tables and rules (100,150) should be deleted 

**How to reproduce it (as minimally and precisely as possible)**:

$ bin/subctl uninstall  --kubeconfig output/kubeconfigs/kind-config-cluster2
? This will completely uninstall Submariner from the cluster. Are you sure you want to continue? Yes
 ✓ Checking if the connectivity component is installed
 ✓ The connectivity component is installed
 ✓ Deleting the Submariner resource - this may take some time 
 ✓ Deleting the Submariner cluster roles and bindings 
 ✓ Deleted the "submariner-diagnose" cluster role and binding
 ✓ Deleted the "submariner-gateway" cluster role and binding
 ✓ Deleted the "submariner-globalnet" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-agent" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-coredns" cluster role and binding
 ✓ Deleted the "submariner-networkplugin-syncer" cluster role and binding
 ✓ Deleted the "submariner-operator" cluster role and binding
 ✓ Deleted the "submariner-routeagent" cluster role and binding
 ✓ Deleting the Submariner namespace "submariner-operator"
 ✓ Deleting the Submariner custom resource definitions
 ✓ Deleted the "brokers.submariner.io" custom resource definition
 ✓ Deleted the "clusterglobalegressips.submariner.io" custom resource definition
 ✓ Deleted the "clusters.submariner.io" custom resource definition
 ✓ Deleted the "endpoints.submariner.io" custom resource definition
 ✓ Deleted the "gateways.submariner.io" custom resource definition
 ✓ Deleted the "globalegressips.submariner.io" custom resource definition
 ✓ Deleted the "globalingressips.submariner.io" custom resource definition
 ✓ Deleted the "servicediscoveries.submariner.io" custom resource definition
 ✓ Deleted the "submariners.submariner.io" custom resource definition
 ✓ Unlabeling gateway nodes

// ssh GW nodes
$ ./../scripts/netshoot_node.sh cluster2-worker
If you don't see a command prompt, try pressing enter.
bash-5.1# ip rule list 
0:      from all lookup local
100:    from all lookup 100
150:    from all lookup 150
32766:  from all lookup main
32767:  from all lookup default

**Anything else we need to know?**:

**Environment**:
KIND (vxlan)

### PR DESCRIPTION
**Pull request by yboaron**
Delete IP rules as part of Submariner uninstall datapath cleanup

Fixes: https://github.com/submariner-io/submariner-operator/issues/1913

Signed-off-by: yboaron <yboaron@redhat.com>

### CODE REVIEW

File: pkg/cable/vxlan/vxlan.go [hunk 1]
```diff
@@ -140,7 +140,7 @@ func (v *vxlan) createVxlanInterface(activeEndPoint string, port int) error {
 
 	v.vxlanIface.vtepIP = vtepIP
 
-	err = v.addIPRule()
+	err = v.configureIPRule(Add)
```
Comment (sridhargaddam) [inline pkg/cable/vxlan/vxlan.go]: Please include the following in the **Commit** message. You added it in the PR, but it should also be in the Commit message. Also, the convention we are using is "Fixes" 

Fixes: https://github.com/submariner-io/submariner-operator/issues/1913

File: pkg/cable/vxlan/vxlan.go [hunk 2]
```diff
@@ -558,5 +569,15 @@ func parseSubnets(subnets []string) []net.IPNet {
 func (v *vxlan) Cleanup() error {
 	klog.Infof("Uninstalling the vxlan cable driver")
 
-	return netlinkAPI.DeleteIfaceAndAssociatedRoutes(VxlanIface, TableID) // nolint:wrapcheck  // No need to wrap this error
+	err := netlinkAPI.DeleteIfaceAndAssociatedRoutes(VxlanIface, TableID)
+	if err != nil {
+		return errors.Wrapf(err, "unable to delete interface %s and associated routes from table %d", VxlanIface, TableID)
```
Comment (sridhargaddam) [inline pkg/cable/vxlan/vxlan.go]: Lets not return if there are any errors. Just log an Error message and we can continue with deleting the remaining items. General idea is to cleanup everything programmed by Submariner, but if there are any transient errors log the error and continue deleting whatever is possible.

File: pkg/cable/vxlan/vxlan.go [hunk 3]
```diff
@@ -257,16 +257,27 @@ func (v *vxlan) getVxlanVtepIPAddress(ipAddr string) (net.IP, error) {
 	return vxlanIP, nil
 }
 
-func (v *vxlan) addIPRule() error {
-	if v.vxlanIface != nil {
-		rule := netlink.NewRule()
-		rule.Table = TableID
-		rule.Priority = TableID
+func (v *vxlan) configureIPRule(operation Operation) error {
```
Comment (sridhargaddam) [inline pkg/cable/vxlan/vxlan.go]: Since the same API is present in route_agent, lets move the API to pkg/netlink/netlink.go file and use it here as well as from route_agent codebase. We can modify this API to take the TableID as argument.

**Review by sridhargaddam — CHANGES_REQUESTED** [review]

File: pkg/cable/vxlan/vxlan.go (hunk 1 above)
Comment (yboaron) [reply pkg/cable/vxlan/vxlan.go]: Thanks for the details, I'll update the commit message.
I copy/paste the 'Resolves' from an operator PR [1], is there a different syntax for operator and submariner repos?

[1]
https://github.com/submariner-io/submariner-operator/pull/1929

File: pkg/cable/vxlan/vxlan.go (hunk 3 above)
Comment (yboaron) [reply pkg/cable/vxlan/vxlan.go]: Yep, that sounds like a good idea.

Do you know if we expect to support rule's parameters other than table Id as arguments?

File: pkg/cable/vxlan/vxlan.go (hunk 1 above)
Comment (skitt) [reply pkg/cable/vxlan/vxlan.go]: The syntax is the same across all repositories. We haven’t documented a preference, as far as I’m aware, but as Sridhar says we seem to mostly use “Fixes”. See [the GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for details.

Some statistics from the operator repository: “Resolves:” appears 8 times, “Fixes:” 65 times, and various other keywords appear many other times (“Resolves-Issue:”, “Resolves issue”, “Fixes-Issue:”, “Fixes issue”, “Closes” etc.).

Comment (yboaron) [reply pkg/cable/vxlan/vxlan.go]: I see, I will use 'Fixes'  from now on.
Thanks Stephen

**Review by sridhargaddam — APPROVED** [review]

File: pkg/cable/vxlan/vxlan.go (hunk 3 above)
Comment (sridhargaddam) [reply pkg/cable/vxlan/vxlan.go]: Currently we don't have such requirement.

File: pkg/netlink/netlink.go [hunk 4]
```diff
@@ -47,8 +47,7 @@ type Basic interface {
 	RouteGet(destination net.IP) ([]netlink.Route, error)
 	RouteList(link netlink.Link, family int) ([]netlink.Route, error)
 	FlushRouteTable(tableID int) error
-	RuleAdd(rule *netlink.Rule) error
-	RuleDel(rule *netlink.Rule) error
+	ConfigureIPRule(operation Operation, tableID int) error
```
Comment (tpantelis) [inline pkg/netlink/netlink.go]: In think we should keep the `RuleAdd` and `RuleDel` primitives as is rather than overloading a single function to do both. Also we can add a shortcut function to create a table rule:

```
func NewTableRule(tableID int) *netlink.Rule {
    rule := netlink.NewRule()
    rule.Table = tableID
    rule.Priority = tableID

    return rule
}
```

File: pkg/netlink/netlink.go [hunk 5]
```diff
@@ -59,7 +58,7 @@ type Basic interface {
 type Interface interface {
 	Basic
 	AddrAddIfNotPresent(link netlink.Link, addr *netlink.Addr) error
-	RuleAddIfNotPresent(rule *netlink.Rule) error
+	RuleAddIfNotPresent(tableID int) error
```
Comment (tpantelis) [inline pkg/netlink/netlink.go]: As outlined above, keep this as is. 

Also we can add a corresponding delete function: `RuleDelIfPresent`.

File: pkg/netlink/netlink.go [hunk 6]
```diff
@@ -125,12 +131,25 @@ func (n *netlinkType) RouteList(link netlink.Link, family int) ([]netlink.Route,
...
+	case Add:
+		err := netlink.RuleAdd(rule)
+		if err != nil && !os.IsExist(err) {
+			return errors.Wrapf(err, "failed to add ip rule %s", rule)
+		}
+	case Delete:
+		err := netlink.RuleDel(rule)
+		if err != nil && !os.IsNotExist(err) {
+			return errors.Wrapf(err, "failed to delete ip rule %s", rule)
+		}
```
Comment (tpantelis) [inline pkg/netlink/netlink.go]: Put this code in `RuleDelIfPresent`.

File: pkg/routeagent_driver/handlers/kubeproxy/gw_transition.go [hunk 7]
```diff
@@ -34,7 +35,7 @@ func (kp *SyncHandler) TransitionToNonGateway() error {
 	// If the active Gateway transitions to a new node, we flush the HostNetwork routing table.
 	kp.updateRoutingRulesForHostNetworkSupport(nil, Flush)
 
-	err := kp.configureIPRule(Delete)
+	err := kp.netLink.ConfigureIPRule(netlinkAPI.Delete, constants.RouteAgentHostNetworkTableID)
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/gw_transition.go]: With the suggested changes, this becomes:

```suggestion
	err := kp.netLink.RuleDelIfPresent(netlinkAPI. NewTableRule(
	constants.RouteAgentHostNetworkTableID))
```

File: pkg/routeagent_driver/handlers/kubeproxy/gw_transition.go [hunk 8]
```diff
@@ -59,7 +60,7 @@ func (kp *SyncHandler) TransitionToGateway() error {
 		klog.Fatalf("Unable to create VxLAN interface on gateway node (%s): %v", kp.hostname, err)
 	}
 
-	err = kp.configureIPRule(Add)
+	err = kp.netLink.ConfigureIPRule(netlinkAPI.Add, constants.RouteAgentHostNetworkTableID)
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/gw_transition.go]: And this becomes:

```suggestion
	err = kp.netLink.RuleAddIfNotPresent(netlinkAPI.NewTableRule( constants.RouteAgentHostNetworkTableID))
```

File: pkg/routeagent_driver/handlers/kubeproxy/uninstall.go [hunk 9]
```diff
@@ -44,6 +44,16 @@ func (kp *SyncHandler) Stop(uninstall bool) error {
 			constants.RouteAgentHostNetworkTableID, err)
 	}
 
+	rule := netlink.NewRule()
+	rule.Table = constants.RouteAgentHostNetworkTableID
+	rule.Priority = constants.RouteAgentHostNetworkTableID
+
+	err = kp.netLink.ConfigureIPRule(netlinkAPI.Delete, constants.RouteAgentHostNetworkTableID)
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/uninstall.go]:
```suggestion
	err = kp.netLink.RuleDelIfPresent(netlinkAPI. NewTableRule( constants.RouteAgentHostNetworkTableID))
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/netlink/netlink.go (hunk 4 above)
Comment (yboaron) [reply pkg/netlink/netlink.go]: OK, I think we can keep to RuleAdd and RuleDel primitives

I'll update the PR

File: pkg/netlink/fake/netlink.go [hunk 10]
```diff
@@ -202,6 +202,17 @@ func (n *basicType) RouteList(link netlink.Link, family int) ([]netlink.Route, e
 	return n.routes[link.Attrs().Index], nil
 }
 
+func (n *basicType) NewTableRule(tableID int) *netlink.Rule {
+	n.mutex.Lock()
+	defer n.mutex.Unlock()
```
Comment (tpantelis) [inline pkg/netlink/fake/netlink.go]: There's no shared memory  to protect so no need to lock.

File: pkg/netlink/netlink.go [hunk 11]
```diff
@@ -47,6 +47,7 @@ type Basic interface {
 	RouteGet(destination net.IP) ([]netlink.Route, error)
 	RouteList(link netlink.Link, family int) ([]netlink.Route, error)
 	FlushRouteTable(tableID int) error
+	NewTableRule(tableID int) *netlink.Rule
```
Comment (tpantelis) [inline pkg/netlink/netlink.go]: This function doesn't need to be part of the interface, ie it can be just package scoped.

File: pkg/routeagent_driver/handlers/kubeproxy/uninstall.go [hunk 12]
```diff
@@ -44,6 +44,16 @@ func (kp *SyncHandler) Stop(uninstall bool) error {
 			constants.RouteAgentHostNetworkTableID, err)
 	}
 
+	rule := netlink.NewRule()
+	rule.Table = constants.RouteAgentHostNetworkTableID
+	rule.Priority = constants.RouteAgentHostNetworkTableID
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/uninstall.go]: The `rule` instance here is unused.

File: pkg/netlink/adapter.go [hunk 13]
```diff
@@ -41,6 +41,15 @@ func (a *Adapter) RuleAddIfNotPresent(rule *netlink.Rule) error {
 	return nil
 }
 
+func (a *Adapter) RuleDelIfPresent(rule *netlink.Rule) error {
+	err := a.RuleDel(rule)
+	if err != nil && !os.IsNotExist(err) {
+		return errors.Wrapf(err, "failed to del rule %s", rule)
```
Comment (tpantelis) [inline pkg/netlink/adapter.go]:
```suggestion
		return errors.Wrapf(err, "failed to delete rule %s", rule)
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Review by tpantelis — APPROVED** [review]
