### PR TITLE
Fix OVN route-agent plugin IPtables handling

### LINKED ISSUE #1488: TCP MSS clamping not fully working on OVN to OVN connections
**What happened**:

    OVN does propagate needfrag ICMPs properly back to pods, hence the pods can't discover the right path MTU, then when crossing clusters. Because of this we use MSS (maximum segment size) clamping, but the MSS clamping only happens on the outgoing path of connections (SYN), not on the incoming connections (SYN,ACK).

That means that the remote clusters will send tcp packets with clamped payload, but we will receive the full MSS (SYN,ACK) from the remote cluster, and send packets bigger than the tunnel can take.

As a result of this many E2E dataplane tests fail.

**What you expected to happen**:

MSS clamping should happen on both directions, and OVN to OVN testing should work with OpenShift.

**How to reproduce it (as minimally and precisely as possible)**:

Setup two OpenShift clusters with OVNKubernetes networking and run e2e verification for dataplane

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #1489: MTU clamping rules for OVN get duplicated many times
I suspect that prepend-unique cannot be used multiple times.
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.244.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.96.0.0/16         tcp flags:0x06/0x02 TCPMSS set 1398
   13   780 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.132.0.0/14        tcp flags:0x06/0x02 TCPMSS set 1398
   52  3120 TCPMSS     tcp  --  *      *       0.0.0.0/0            172.31.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      ovn-k8s-sub0  0.0.0.0/0            172.30.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
  273 76898 ACCEPT     all  --  br-ex  ovn-k8s-sub0  0.0.0.0/0            0.0.0.0/0           
  456  298K ACCEPT     all  --  ovn-k8s-sub0 br-ex   0.0.0.0/0            0.0.0.0/0           
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            172.31.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.244.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.96.0.0/16         tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.132.0.0/14        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      ovn-k8s-sub0  0.0.0.0/0            172.30.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.96.0.0/16         tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.132.0.0/14        tcp flags:0x06/0x02 TCPMSS set 1398
   11   660 TCPMSS     tcp  --  *      *       0.0.0.0/0            172.31.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
  195 11700 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.244.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
  195 11700 TCPMSS     tcp  --  *      ovn-k8s-sub0  0.0.0.0/0            172.30.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
   13   780 TCPMSS     tcp  --  *      *       0.0.0.0/0            172.31.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
  127  7620 TCPMSS     tcp  --  *      *       0.0.0.0/0            10.132.0.0/14        tcp flags:0x06/0x02 TCPMSS set 1398
  129  7740 TCPMSS     tcp  --  *      ovn-k8s-sub0  0.0.0.0/0            172.30.0.0/16        tcp flags:0x06/0x02 TCPMSS set 1398
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22624 flags:0x17/0x02 reject-with icmp-port-unreachable
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22623 flags:0x17/0x02 reject-with icmp-port-unreachable

```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mangelajo**
See the individual commits:

- refactor out UpdateChainRules for reuse
- Create separete forward and clamping chains, use UpdateChain
- Add incomming SYN , SYN/ACK clamping on responses to fix the full TCP negotiation
- Make sure that UpdateChainRules works for us 
- Create iptables interface only once in the OVN route-agent handler 

Closes-Issue: #1488 
Closes-Issue: #1489

### CODE REVIEW

File: pkg/iptables/iptables.go [hunk 1]
```diff
@@ -138,3 +140,51 @@ func InsertUnique(ipt Interface, table, chain string, position int, ruleSpec []s
 
 	return nil
 }
+
+// UpdateChainRules ensures that the rules in the list are the ones in rules, without any preference for the order,
+// any stale rules will be removed from the chain, and any missing rules will be added.
+func UpdateChainRules(ipt Interface, table, chain string, rules [][]string) error {
```
Comment (skitt) [inline pkg/iptables/iptables.go:146]: This deserves a unit test ;-)

**Review by skitt — APPROVED** [review]

File: pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go [hunk 2]
```diff
@@ -112,62 +102,48 @@ func (ovn *Handler) getForwardingRuleSpecs() ([][]string, error) {
...
-	ipt, err := iptables.New()
-	if err != nil {
-		return errors.Wrap(err, "error initializing iptables")
-	}
+const forwardingSubmarinerMSSClampChain = "SUBMARINER-FWD-MSSCLAMP"
+const forwardingSubmarinerFWDChain = "SUBMARINER-FORWARD"
 
-	ruleSpecs, err := ruleGen()
+func (ovn *Handler) setupForwardingIptables() error {
+	ipt, err := submiptables.New()
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go]: We can initialize submiptables.New() once during bootup, store it in Handler and re-use it in the APIs. Calling iptables.New() will internally call exec, parseIPTablesVersion etc which can be avoided.

File: pkg/iptables/iptables.go (hunk 1 above)
Comment (mangelajo) [reply pkg/iptables/iptables.go:146]: You're right, since now ipt Interface really allows that. I'm adding that on a follow up PR, starting now. 

Thanks for the quick review.

**Review by sridhargaddam — CHANGES_REQUESTED** [review]
LGTM, one small comment about iptables initialization.

File: pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go (hunk 2 above)
Comment (mangelajo) [reply pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go]: Ack, makes sense, I will create iptables interface once for the ovn handler, and then we can use it as much as we want.

I'll add another commit for that.

**Comment by mangelajo** [comment]
Hi @sridhargaddam I addressed your comments on a separate commit. Let me know how it looks.

**Comment by mangelajo** [comment]
@sridhargaddam the ovn failures are the usual suspect unrelated to this patch

```
[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:186

```

Do you have a sec to re-review and merge, the changes are on the last commit.

**Review by sridhargaddam — APPROVED** [review]
