### PR TITLE
Retry the lookup for the loadbalancer before exiting

### LINKED ISSUE #1422: When submariner-gateway is configured behind a loadbalancer it will exit with Error/CrashBackoff if the LoadBalancer isn't ready
Submariner-gateway reads the loadbalancer, and it isn't ready yet, exits with error...
that makes the loadbalancer more unstable, because submariner-gateway is one of the 
endpoints of the LoadBalancer.

The proposed fix is to wait for the LoadBalancer to be fully ready & functional, with some backoff & timeout.

This increases the likeliness of https://github.com/submariner-io/submariner/issues/1410

### PR DESCRIPTION
**Pull request by mangelajo**
Fixes-Issue: #1422
Related-Issue: #1410

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

### CODE REVIEW

**Review by Jaanki — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Comment by mangelajo** [comment]
@tpantelis @skitt can you have an eye on this one ? I need a core vote :)

File: pkg/endpoint/public_ip.go [hunk 1]
```diff
@@ -108,30 +111,44 @@ func publicIP(clientset kubernetes.Interface, namespace, value string) (string,
...
-	}
-
-	if ingress.Hostname != "" {
-		ip, err := publicDNSIP(clientset, namespace, ingress.Hostname)
-		if err != nil {
-			return "", errors.Wrapf(err, "error resolving LoadBalancer ingress HostName %q", ingress.Hostname)
+	err = retry.OnError(retryConfig, func(err error) bool {
+		klog.Infof("Waiting for LoadBalancer to be ready: %s", err)
+		return true
+	}, func() error {
```
Comment (tpantelis) [inline pkg/endpoint/public_ip.go:126]: Shouldn't you get the service here or am I missing something?

Comment (sridhargaddam) [reply pkg/endpoint/public_ip.go:126]: I think so...

Comment (mangelajo) [reply pkg/endpoint/public_ip.go:126]: oh my, yes :)

Comment (mangelajo) [reply pkg/endpoint/public_ip.go:126]: Sorry for the update delay. @tpantelis thanks for catching this important "detail" ;) Without this it would have only worked waiting for the dns resolution, not the ingress.

**Review by tpantelis — APPROVED** [review]

**Comment by mangelajo** [comment]
Force pushed to fix the protobuf import issue: 

https://github.com/submariner-io/submariner/pull/1423/checks?check_run_id=2972328032#step:4:12

I wonder why the go.mod locally pulls protobuf, while it doesn't on CI ... hmmm...
