### PR TITLE
Fix stale iptable rule and globalip leak

### LINKED ISSUE #2388: Globalnet: Stale iptable rule and globalIP leak during stress testing
**What happened**:
When we create a globalEgressIP targetting a namespace and immediately delete it (using some script), it was seen that there is a race condition leading to a stale iptable rule on the Gateway node as well as the associated globalIP not added back to the free pool.

Steps to reproduce the issue:
```
apiVersion: submariner.io/v1
kind: GlobalEgressIP
metadata:
  name: ns-egressip
  namespace: subm-kindnet-workaround
spec:
  numberOfIPs: 1
```

Apply the above YAML in a globalnet deployment preferably using a simple shell script with the following contents.

```
#!/bin/sh

kubectl apply -f ns-egressip.yaml
kubectl delete -f ns-egressip.yaml
``` 

When this is done, you can notice the following logs in Globalnet pod.

```
[90m2023-04-01T17:56:10.351Z[0m [32mINF[0m ..essip_controller.go:137 Globalnet            Processing created GlobalEgressIP "subm-kindnet-workaround/ns-egressip", NumberOfIPs: 1, PodSelector: (*v1.LabelSelector)(nil), Status: v1.GlobalEgressIPStatus{Conditions:[]v1.Condition(nil), AllocatedIPs:[]string(nil)}
[90m2023-04-01T17:56:10.351Z[0m [32mINF[0m ..essip_controller.go:199 Globalnet            Allocating 1 global IP(s) for "subm-kindnet-workaround/ns-egressip"
[90m2023-04-01T17:56:10.351Z[0m [33mDBG[0m ../pkg/ipset/ipset.go:352 IPSet                Running ipset [create SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM hash:ip -exist]
[90m2023-04-01T17:56:10.352Z[0m [33mDBG[0m ..s/iptables/iface.go:275 IPTables             Installing iptable egress rules for Namespace "subm-kindnet-workaround/ns-egressip": -p all -m set --match-set SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM src -m mark --mark 0xC0000/0xC0000 -j SNAT --to 242.254.2.253
[90m2023-04-01T17:56:10.357Z[0m [32mINF[0m ..essip_controller.go:260 Globalnet            Allocated [242.254.2.253] global IP(s) for "subm-kindnet-workaround/ns-egressip"
[90m2023-04-01T17:56:10.458Z[0m [32mINF[0m ..essip_controller.go:354 Globalnet            Started pod watcher for "subm-kindnet-workaround/ns-egressip"
[90m2023-04-01T17:56:10.458Z[0m [32mINF[0m ..base_controllers.go:207 Globalnet            Updated: &v1.GlobalEgressIPStatus{Conditions:[]v1.Condition{v1.Condition{Type:"Allocated", Status:"True", ObservedGeneration:0, LastTransitionTime:time.Date(2023, time.April, 1, 17, 56, 10, 356993959, time.Local), Reason:"Success", Message:"Allocated 1 global IP(s)"}}, AllocatedIPs:[]string{"242.254.2.253"}}
[90m2023-04-01T17:56:10.460Z[0m [33mDBG[0m ..gress_pod_watcher.go:96 Globalnet            Pod "subm-kindnet-workaround/dummypod-zj6x7" with IP 10.129.1.2 created/updated
[90m2023-04-01T17:56:10.460Z[0m [33mDBG[0m ../pkg/ipset/ipset.go:352 IPSet                Running ipset [add SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM 10.129.1.2 -exist]
[90m2023-04-01T17:56:10.465Z[0m [32mINF[0m ..essip_controller.go:137 Globalnet            Processing deleted GlobalEgressIP "subm-kindnet-workaround/ns-egressip", NumberOfIPs: 1, PodSelector: (*v1.LabelSelector)(nil), Status: v1.GlobalEgressIPStatus{Conditions:[]v1.Condition(nil), AllocatedIPs:[]string(nil)}
[90m2023-04-01T17:56:10.465Z[0m [33mDBG[0m ../pkg/ipset/ipset.go:352 IPSet                Running ipset [destroy SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM]
[90m2023-04-01T17:56:10.467Z[0m [33mDBG[0m ..gress_pod_watcher.go:96 Globalnet            Pod "subm-kindnet-workaround/dummypod-5fvkt" with IP 10.129.0.5 created/updated
[90m2023-04-01T17:56:10.467Z[0m [33mDBG[0m ../pkg/ipset/ipset.go:352 IPSet                Running ipset [add SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM 10.129.0.5 -exist]
[90m2023-04-01T17:56:10.481Z[0m [1m[31mERR[0m[0m ..essip_controller.go:300 Globalnet            Error destroying the ipSet "SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM" for "subm-kindnet-workaround/ns-egressip" [36merror=[0m[31m"error destroying set \"SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM\": exit status 1 (ipset v7.15: Set cannot be destroyed: it is in use by a kernel component\n)"[0m
[90m2023-04-01T17:56:10.483Z[0m [33mDBG[0m ..gress_pod_watcher.go:96 Globalnet            Pod "subm-kindnet-workaround/dummypod-zr8pt" with IP 10.129.2.2 created/updated
[90m2023-04-01T17:56:10.483Z[0m [33mDBG[0m ../pkg/ipset/ipset.go:352 IPSet                Running ipset [add SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM 10.129.2.2 -exist]
[90m2023-04-01T17:56:10.487Z[0m [32mINF[0m ..essip_controller.go:137 Globalnet            Processing deleted GlobalEgressIP "subm-kindnet-workaround/ns-egressip", NumberOfIPs: 1, PodSelector: (*v1.LabelSelector)(nil), Status: v1.GlobalEgressIPStatus{Conditions:[]v1.Condition(nil), AllocatedIPs:[]string(nil)}
[90m2023-04-01T17:56:10.487Z[0m [33mDBG[0m ../pkg/ipset/ipset.go:352 IPSet                Running ipset [destroy SM-GN-X5PDWKL6RJ2CRMZ4KH376JEYM]
```

When the delete notification comes for the ns-egressip object, the AllocatedIPs field is empty (even though in the previous operation Globalnet controller has allocated and updated the object with the globalIPs).

Note: If you add a small delay between the creation, deletion of the globalEgressIP Object, the issue will not be seen.
 
**Environment**:
- Cloud provider or hardware configuration: KIND with latest devel (as on 31st March, 2023)

### PR DESCRIPTION
**Pull request by sridhargaddam**
In this PR, the Globalnet controller, caches the AllocatedIPs for a globalEgressIP object and refers to it when the delete notification is seen (when the AllocatedIPs field is empty), which is sometimes noticed when the globalEgressIP object is created and immediately deleted.

Fixes: https://github.com/submariner-io/submariner/issues/2388

### CODE REVIEW

File: pkg/globalnet/controllers/global_egressip_controller.go [hunk 1]
```diff
@@ -291,6 +291,12 @@ func (c *globalEgressIPController) onDelete(numRequeues int, globalEgressIP *sub
 
 	namedIPSet := c.newNamedIPSet(key)
 
+	if len(globalEgressIP.Status.AllocatedIPs) == 0 && len(podWatcher.AllocatedIPs) > 0 {
+		// Refer to issue for more details: https://github.com/submariner-io/submariner/issues/2388
```
Comment (skitt) [inline pkg/globalnet/controllers/global_egressip_controller.go:295]: Wouldn’t it be better to requeue instead, so the delete will be retried later (once the creation has been processed and the cache updated)?

**Review by skitt — CHANGES_REQUESTED** [review]

File: pkg/globalnet/controllers/global_egressip_controller.go (hunk 1 above)
Comment (sridhargaddam) [reply pkg/globalnet/controllers/global_egressip_controller.go:295]: That is what the existing code was doing when it failed to delete the IPset (as its referenced in the stale IPtable rule). I noticed that even as part of the delete re-queue event the globalEgressIPs.Status.AllocatedIPs field was empty.

**Comment by sridhargaddam** [comment]
Logs, with this fix:

Screenshot from 2023-04-03 12-14-00

File: pkg/globalnet/controllers/global_egressip_controller.go (hunk 1 above)
Comment (skitt) [reply pkg/globalnet/controllers/global_egressip_controller.go:295]: It feels like we’re papering over the issue — what happens with this fix if you create two `GlobalEgressIP`s and delete them in quick succession?

Comment (sridhargaddam) [reply pkg/globalnet/controllers/global_egressip_controller.go:295]: A GlobalEgressIP Object can target a set of Pods or the entire namespace. In both the cases, the Globalnet Controller creates a [podWatcher](https://github.com/submariner-io/submariner/blob/23af29dd07da2b4341cba7a520e470ae03a635b0/pkg/globalnet/controllers/global_egressip_controller.go#L345) internally for EACH of the globalEgress object. In this PR, we are storing the AllocatedGlobalIPs as part of the respective [podWatcher instance](https://github.com/submariner-io/submariner/blob/23af29dd07da2b4341cba7a520e470ae03a635b0/pkg/globalnet/controllers/types.go#L125), so even if we create two (or more) GlobalEgressIPs in parallel and delete them, it should work as expected.

Anyways, I'm open to any suggestions in improving it. 
CC: @tpantelis

Comment (skitt) [reply pkg/globalnet/controllers/global_egressip_controller.go:295]: Ah right, that’s the information I was missing. Thanks!

**Review by skitt — APPROVED** [review]

File: pkg/globalnet/controllers/types.go [hunk 2]
```diff
@@ -123,10 +123,11 @@ type globalEgressIPController struct {
...
 type egressPodWatcher struct {
-	stopCh      chan struct{}
-	ipSetName   string
-	namedIPSet  ipset.Named
-	podSelector *metav1.LabelSelector
+	stopCh       chan struct{}
+	ipSetName    string
+	namedIPSet   ipset.Named
+	podSelector  *metav1.LabelSelector
+	AllocatedIPs []string
```
Comment (tpantelis) [inline pkg/globalnet/controllers/types.go]: nit - for consistency.

```suggestion
	allocatedIPs []string
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Review by tpantelis — APPROVED** [review]

**Review by yboaron — APPROVED** [review]

**Comment by dfarrell07** [comment]
Release notes: https://github.com/submariner-io/submariner/pull/2451
