### PR TITLE
Initialize libovsdb clients to any DB

### LINKED ISSUE #1878: submariner-networkplugin-syncer fails to start
**What happened**:

When submariner is deployed with a cluster with OVNKubernetes CNI, submariner-networkplugin-syncer fails to start with this error.
`
F0620 21:36:09.217221       1 main.go:67] Error registering the handlers: Event handler "ovn-sync-handler" failed to initialize: error creating NBDB connection: error connecting to ovsdb: failed to connect to ssl:ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local:9641: endpoint is not leader`

It starts working when the first IP  dig @<opnshift-dns-ip> ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local
of the headless service is the current kuberntes master.

For example assume 192.168.198.14 is the current master. If the dig output is as below it does not work.
```
$dig @172.90.0.10 ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local
ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local. 5 IN A 192.168.198.239
ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local. 5 IN A 192.168.198.14
ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local. 5 IN A 192.168.198.181
```

Now if we delete pods with IP 192.168.198.239(one of ovnkube-master pod in openshift-ovn-kubernetes namespace)  . The output of dig changes as below and it starts working

```
$dig @172.90.0.10 ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local
ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local. 5 IN A 192.168.198.14
ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local. 5 IN A 192.168.198.181
ovnkube-db.openshift-ovn-kubernetes.svc.cluster.local. 5 IN A 192.168.198.239

```

In short, It starts working when submariner-networkplugin-syncer connects to correct leader.

**What you expected to happen**:

The submariner-networkplugin-syncer pod should be up and running

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a Openshift 4.11 cluster and deploy submariner. If it is working try deleting the current ovn master and submariner-networkplugin-syncer.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by astoycos**
Setup the libovsdb clients with `WithLeaderOnly(false)`
since the submariner clients are not write intensive
and the changes written to a non-leader db should be
mirrored throughout the cluster.

This allows us to not have to track the DB leader in the
cluster saving some overhead.

Fixes #1878

### CODE REVIEW

**Review by aswinsuryan — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

File: pkg/networkplugin-syncer/handlers/ovn/connection.go [hunk 1]
```diff
@@ -124,7 +124,7 @@ func createLibovsdbClient(dbAddress string, tlsConfig *tls.Config, dbModel model
 		// take longer than a normal ovsdb operation. Give it a bit more time so
 		// we don't time out and enter a reconnect loop.
 		libovsdbclient.WithReconnect(connectTimeout, &backoff.ZeroBackOff{}),
-		libovsdbclient.WithLeaderOnly(true),
+		libovsdbclient.WithLeaderOnly(false),
```
Comment (skitt) [inline pkg/networkplugin-syncer/handlers/ovn/connection.go]: We might as well delete this since it’s the default setting:

```suggestion
```

**Review by skitt — CHANGES_REQUESTED** [review]
Note that links to the CoreOS Slack aren’t accessible to people outside Red Hat, and should therefore be avoided — if it’s important, it’s better to summarize discussions in the commit message (however the added information isn’t significant here).

**Comment by astoycos** [comment]
ACK Agreed @skitt Sorry about that :/

File: pkg/networkplugin-syncer/handlers/ovn/connection.go (hunk 1 above)
Comment (astoycos) [reply pkg/networkplugin-syncer/handlers/ovn/connection.go]: Done

**Review by sridhargaddam — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by nyechiel** [comment]
@skitt can you please make sure this is being backported?

**Comment by nyechiel** [comment]
@aswinsuryan will handle the backport to `release-0.13`. Thanks!
