### PR TITLE
Fix issues with Pinger on relection as leader

### LINKED ISSUE #3008: Invalid healthchecker counters when the leader is relected
**What happened**:
The health checker county er is not getting updated when a gateway node lose leader election and get elected again.
When the 

**What you expected to happen**:
The counters should have the updated values

**How to reproduce it (as minimally and precisely as possible)**:
Try to simulate a leader re-election
**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by aswinsuryan**
The pinger  for remote endpoints are started
when a node is relected as a leader, once it
looses it leadership.

Fixes: https://github.com/submariner-io/submariner/issues/3008

### CODE REVIEW

File: pkg/cableengine/healthchecker/healthchecker.go [hunk 1]
```diff
@@ -116,6 +120,19 @@ func (h *controller) Start(stopCh <-chan struct{}) error {
...
+	if err != nil {
+		return errors.Wrap(err, "error listing endpoints")
+	}
+
+	endpointList := endpoints.Items
+
+	for i := range endpointList {
+		h.endpointCreatedOrUpdated(&endpointList[i], 0)
+	}
+
```
Comment (tpantelis) [inline pkg/cableengine/healthchecker/healthchecker.go]: So this gets all `Endpoints` and runs them through `endpointCreatedOrUpdated`. This duplicates what the informer already does so I assume this is to handle subsequent calls to `Start`. While this will reprocess current `Endpoints`, the `endpointWatcher` will not be restarted so it will not handle updates to remote `Endpoints`.

The real problem is that the `controller` is not re-startable and the caller assumes it is. To make it so, we need to create the `endpointWatcher` instance in the `Start` method so it's recreated on each call.

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/cableengine/healthchecker/healthchecker.go (hunk 1 above)
Comment (aswinsuryan) [reply pkg/cableengine/healthchecker/healthchecker.go]: thanks for the detailed explanation. Made the changes.

**Comment by tpantelis** [comment]
I submitted https://github.com/submariner-io/submariner/pull/3017/commits/161240975ca0e4b419d50af883851011324ad070 to update the unit tests to test stopping and restarting.

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]
