### PR TITLE
Accept ULA IPv6 addresses as valid local IPs

### LINKED ISSUE #3482: Submariner gateway fails to detect valid local IPv6  for endpoint in OCP dual-stack cluster on OpenStack
In an OCP dual-stack environment on OpenStack, Submariner gateway fails to detect a valid local IPv6 address for endpoint. 

The detection logic rejects available IPv6 addresses as invalid, causing the gateway to log errors and fail to initialize properly.

Gateway pod logs [1] 

IPv6 addresses and routes in node [2] 

[1] 

`2025-07-01T10:38:17.110Z WRN ..endpoint/local_ip.go:73 Endpoint             IP "fd1e:1111:1111:1111:f816:3eff:fe4a:1e24" returned from Dial isn't usable - trying to find another IP from the same interface
2025-07-01T10:38:17.114Z WRN ..endpoint/local_ip.go:80 Endpoint             Failed to retrieve valid IPv6 address for "fd1e:1111:1111:1111:f816:3eff:fe4a:1e24": no valid global IPv6 found on interface "br-ex" for IP "fd1e:1111:1111:1111:f816:3eff:fe4a:1e24"
2025-07-01T10:38:17.114Z FTL ..endpoint/local_ip.go:86 Endpoint             Error getting local IPv6 error="couldn't find route for family 6"
`

[2]

`sh-5.2# ip -6 a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
5: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7950 state UNKNOWN qlen 1000
    inet6 fd69::2/112 scope global nodad deprecated 
       valid_lft forever preferred_lft 0sec
    inet6 fd1e:1111:1111:1111:f816:3eff:fe4a:1e24/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe4a:1e24/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
7: ovn-k8s-mp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UNKNOWN qlen 1000
    inet6 fd01:0:0:6::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::858:aff:fe81:202/64 scope link 
       valid_lft forever preferred_lft forever
8: genev_sys_6081: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 state UNKNOWN qlen 1000
    inet6 fe80::40ba:e3ff:feb5:b3a/64 scope link 
       valid_lft forever preferred_lft forever
9: 39eec44e9d16a66@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::7cd9:7fff:fe76:b5d8/64 scope link 
       valid_lft forever preferred_lft forever
10: f799fb480b9c715@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::70c7:f0ff:febe:8d90/64 scope link 
       valid_lft forever preferred_lft forever
20: b7032db20219f36@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::9477:e1ff:feb4:14c/64 scope link 
       valid_lft forever preferred_lft forever
21: 052d580f587efae@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::d067:86ff:fe65:bb89/64 scope link 
       valid_lft forever preferred_lft forever
1636: 4048986dee609c4@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::dc15:dfff:fed3:aaf0/64 scope link 
       valid_lft forever preferred_lft forever
1934: 45786af20464187@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::cd7:81ff:fe91:f89b/64 scope link 
       valid_lft forever preferred_lft forever
1935: 94e71cb39e036c2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::64b5:d5ff:fe09:e144/64 scope link 
       valid_lft forever preferred_lft forever
1942: 104657bf513da2e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::a889:3dff:fe8e:be59/64 scope link 
       valid_lft forever preferred_lft forever
1943: a4dbcd11f38632d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7850 state UP 
    inet6 fe80::e414:b3ff:fe73:8f40/64 scope link 
       valid_lft forever preferred_lft forever

sh-5.2# ip -6 route show 
::1 dev lo proto kernel metric 256 pref medium
fd01:0:0:6::/64 dev ovn-k8s-mp0 proto kernel metric 256 pref medium
fd01::/48 via fd01:0:0:6::1 dev ovn-k8s-mp0 metric 1024 pref medium
fd02::/112 via fd69::4 dev br-ex src fd69::2 metric 1024 mtu 7850 pref medium
fd1e:1111:1111:1111::/64 dev br-ex proto ra metric 48 pref medium
fd69::1 dev br-ex src fd1e:1111:1111:1111:f816:3eff:fe4a:1e24 metric 1024 pref medium
fd69::3 via fd01:0:0:6::1 dev ovn-k8s-mp0 metric 1024 pref medium
fd69::/112 dev br-ex proto kernel metric 256 pref medium
fe80::/64 dev ovn-k8s-mp0 proto kernel metric 256 pref medium
fe80::/64 dev genev_sys_6081 proto kernel metric 256 pref medium
fe80::/64 dev 39eec44e9d16a66 proto kernel metric 256 pref medium
fe80::/64 dev f799fb480b9c715 proto kernel metric 256 pref medium
fe80::/64 dev b7032db20219f36 proto kernel metric 256 pref medium
fe80::/64 dev 052d580f587efae proto kernel metric 256 pref medium
fe80::/64 dev 4048986dee609c4 proto kernel metric 256 pref medium
fe80::/64 dev 45786af20464187 proto kernel metric 256 pref medium
fe80::/64 dev 94e71cb39e036c2 proto kernel metric 256 pref medium
fe80::/64 dev 104657bf513da2e proto kernel metric 256 pref medium
fe80::/64 dev a4dbcd11f38632d proto kernel metric 256 pref medium
fe80::/64 dev br-ex proto kernel metric 1024 pref medium
default via fe80::f816:3eff:fecf:d032 dev br-ex proto ra metric 48 pref medium
`

### PR DESCRIPTION
**Pull request by yboaron**
Update local IP detection logic to permit ULA (Unique Local Address)
IPv6 addresses — the IPv6 equivalent of private IPv4 addresses — as valid
candidates for Submariner private IP.

This change is necessary to support environments where clusters assign
ULA IPv6 ranges for node IP addresses.

Fixes: https://github.com/submariner-io/submariner/issues/3482

### CODE REVIEW

**Comment by yboaron** [comment]
cc @aswinsuryan

File: pkg/endpoint/local_ip.go [hunk 1]
```diff
@@ -32,6 +32,14 @@ var (
 		k8snet.IPv4: "8.8.8.8",
 		k8snet.IPv6: "2001:4860:4860::8888",
 	}
+
+	// These addresses are used internally by OVN-Kubernetes CNI
+	// and should not be used as local IPs.
+	infraInternalIPs = map[string]struct{}{
+		"fd69::2":       {},
+		"169.254.169.2": {},
+	}
```
Comment (tpantelis) [inline pkg/endpoint/local_ip.go]: Could use a `Set` here.

```suggestion
        import "k8s.io/apimachinery/pkg/util/sets"
        ...
        
	infraInternalIPs  := sets.New("fd69::2", "169.254.169.2")
```

Comment (skitt) [reply pkg/endpoint/local_ip.go]: +1 but please use `k8s.io/utils` sets rather than `apimachinery`.

File: pkg/endpoint/local_ip.go [hunk 2]
```diff
@@ -88,14 +92,12 @@ func GetLocalIPForDestination(dst string, family k8snet.IPFamily) string {
 	return localIP
 }
 
-func isValidGlobalIPv6(ip net.IP) bool {
-	// fd00::/8 - avoid locally assigned ULA
-	if ip.To16() == nil || ip.IsLoopback() || ip.IsLinkLocalUnicast() ||
-		ip[0] == 0xfd {
+func isAcceptableIPv6(ip net.IP) bool {
+	if ip.To16() == nil || ip.IsLoopback() || ip.IsLinkLocalUnicast() || ip.String() == infraInternalIPv6 {
```
Comment (tpantelis) [inline pkg/endpoint/local_ip.go]: Is `ip.String()` guaranteed to yield the same string form as `infraInternalIPv6` as there can be different ways of representing an IPv6 address as a string wrt to abbreviating? Perhaps it would be safer to do:

```
infraInternalIPv6 = net.ParseIP("fd69::2")
...

ip = ip.To16()
return ip != nil && !ip.IsLoopback() && !ip.IsLinkLocalUnicast() && !ip.Equal(infraInternalIPv6)
```

Comment (yboaron) [reply pkg/endpoint/local_ip.go]: good point , I'll update it.

**Review by aswinsuryan — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Review by skitt — APPROVED** [review]
