### PR TITLE
Fix network discovery issue in ovn non-ic deployments

### LINKED ISSUE #2673: Fail to run submariner with OCP 4.13.9 on AWS
**What happened**:
Using `subctl` version 0.16.0-m4
submariner-route-agent are not running - no connection to other cluster.
From logs:
 `Error registering the handlers: Event handler "ovn-hostroutes-handler" failed to initialize: error getting connection handler to connect to OvnDB: error creating NBDB connection: error connecting to ovsdb: failed to connect to unix:/var/run/ovn-ic/ovnnb_db.sock: failed to open connection: dial unix /var/run/ovn-ic/ovnnb_db.sock: connect: connection refused
`
**What you expected to happen**:
all pods will run

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:
[submariner-gather.tar.gz](https://github.com/submariner-io/submariner/files/12537220/submariner-gather.tar.gz)

### PR DESCRIPTION
**Pull request by aswinsuryan**
Fix network discovery issue in ovn non-ic deployments

Fixes: https://github.com/submariner-io/submariner/issues/2673

### CODE REVIEW

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 1]
```diff
@@ -192,12 +188,31 @@ func discoverOvnKubernetesNetwork(ctx context.Context, k8sClientset clientset.In
 		return "", err
 	}
 
+	ovnPod, err := FindPod(ctx, k8sClientset, "app=ovnkube-node")
+	if err != nil || ovnPod == nil {
```
Comment (yboaron) [inline pkg/routeagent_driver/handlers/ovn/connection.go]: Maybe use two separate ifs?
```

if err != nil {
   return "", err
}
if ovnPod == nil {
   return defaultOVNOpenshiftUnixSocket, nil
}
```

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 2]
```diff
@@ -192,12 +188,31 @@ func discoverOvnKubernetesNetwork(ctx context.Context, k8sClientset clientset.In
...
 	} else {
-		nbdbAddress, err = discoverOvnNodeClusterNetwork(ctx, k8sClientset, zoneName)
+		if zoneName == "" {
+			return defaultOVNOpenshiftUnixSocket, nil
+		}
+
+		nbdbAddress, err = discoverOvnNodeClusterNetwork(ctx, k8sClientset, zoneName, ovnPod)
 	}
 
 	if err != nil {
```
Comment (yboaron) [inline pkg/routeagent_driver/handlers/ovn/connection.go:249]: To which err does this if refer to?

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 1 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 2 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:249]: Refactored to make it clear.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 3]
```diff
@@ -192,39 +188,48 @@ func discoverOvnKubernetesNetwork(ctx context.Context, k8sClientset clientset.In
...
+		if zoneName == "" {
+			return defaultOVNOpenshiftUnixSocket, nil
+		}
 
-	if err != nil {
-		return "", err
+		nbdbAddress, err = discoverOvnNodeClusterNetwork(ctx, k8sClientset, zoneName, ovnPod)
+		if err != nil {
+			return "", err
+		}
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go]: It would be hard to understand/maintain this code without a proper understanding of how the pods/services are deployed with OVN/OVN-IC. 

Can you please add a comment explaining how the discovery works.
1. For KIND OVN non-IC deployments.
2. KIND OVN-IC deployments
3. OpenShift OVN deployments
4. OpenShift OVN-IC deployments.

**Review by sridhargaddam — DISMISSED** [review]

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 3 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 4]
```diff
@@ -186,45 +182,70 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+        these are not db endpoints. Here we will return default Openshift socket path
+*/
+
 func discoverOvnKubernetesNetwork(ctx context.Context, k8sClientset clientset.Interface, zoneName string) (string, error) {
 	ovnDBPod, err := FindPod(ctx, k8sClientset, "name=ovnkube-db")
 	if err != nil {
 		return "", err
 	}
 
+	ovnPod, err := FindPod(ctx, k8sClientset, "app=ovnkube-node")
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go]: In the description above, no where we talk about ovnkube-node, but this code is looking for this pod and if not found, its returning defaultOVNOpenshiftUnixSocket.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 5]
```diff
@@ -186,45 +182,70 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
 	var nbdbAddress string
+	_, err = k8sClientset.CoreV1().Services(ovnPod.Namespace).Get(ctx, ovnKubeService, metav1.GetOptions{})
 
-	if ovnDBPod != nil {
-		nbdbAddress, err = discoverOvnDBClusterNetwork(ctx, k8sClientset, ovnDBPod)
-	} else {
-		nbdbAddress, err = discoverOvnNodeClusterNetwork(ctx, k8sClientset, zoneName)
+	// Openshift deployments uses DB that are parts of the node pod and there will not be a separate db pod for non-ic.
+	if ovnDBPod == nil && err == nil {
+		return defaultOVNNBDB, nil
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go]: Is the defaultOVNNBDB only applicable for KIND deployments? If so, can we use Kind as part of the constantName to make it easy while reading this code?

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 4 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go]: it is to get the ovn namespace. This particular condition will hit in normal cases. But I just thought would return this value as the CNI is OVN. I changed the comment to include the pod.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 6]
```diff
@@ -186,45 +182,70 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
 	}
+	// Kind deployments will have a db pod and db service for non-ic.
+	if ovnDBPod != nil && err == nil {
+		nbdbAddress = discoverOvnDBClusterNetwork(ovnDBPod)
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go]:
```suggestion
                // This is a Kind non-IC deployment 
		nbdbAddress = discoverOvnDBClusterNetwork(ovnDBPod)
```

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 5 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go]: It is applicable only for openshift , changed the name.

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 6 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 7]
```diff
@@ -186,45 +182,71 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+	// Openshift deployments uses DB that are parts of the node pod and there will not be a separate db pod for non-ic.
+	if ovnDBPod == nil && err == nil {
+		return defaultOpenshiftOVNNBDB, nil
 	}
+	// Kind deployments will have a db pod and db service for non-ic.
+	if ovnDBPod != nil && err == nil {
+		// This is a Kind non-IC deployment
+		nbdbAddress = discoverOvnDBClusterNetwork(ovnDBPod)
+	} else {
+		if zoneName == "" {
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go]: As discussed on slack, please refactor this code and keep the comments in sync with the new code. Thanks.

Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 8]
```diff
@@ -186,45 +188,85 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+
+func discoverOpenshiftOvnKubernetesNetwork(ctx context.Context, k8sClientSet clientset.Interface) (string, error) {
+	ovnPod, err := FindPod(ctx, k8sClientSet, "app=ovnkube-node")
+	if err != nil {
+		return "", errors.Wrap(err, "error finding a pod with label \"app=ovnkube-node\"")
+	}
+
+	_, err = k8sClientSet.CoreV1().Services(ovnPod.Namespace).Get(ctx, ovnKubeService, metav1.GetOptions{})
+	if err == nil {
+		return defaultOpenshiftOVNNBDB, nil
```
Comment (yboaron) [inline pkg/routeagent_driver/handlers/ovn/connection.go:222]: According to code it seems that there are only two options 
* non-ic ==> when both pod and service exist
* rest of the cases 
Is it correct?

 if the answer is yes , maybe it would be better to have a separate boolean function for detecting non-ic deployment.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 9]
```diff
@@ -186,45 +188,85 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+		return discoverKindOvnDBClusterNetwork(ctx, ovnDBPod, k8sClientSet)
 	}
 
+	ovnPod, err := FindPod(ctx, k8sClientSet, "app=ovnkube-node")
 	if err != nil {
 		return "", err
 	}
 
-	return nbdbAddress, nil
+	return discoverKindOvnNodeClusterNetwork(ctx, k8sClientSet, zoneName, ovnPod)
```
Comment (yboaron) [inline pkg/routeagent_driver/handlers/ovn/connection.go:253]: Don't you need to check that ovnPod is != nil ?

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 10]
```diff
@@ -186,45 +188,85 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+	return discoverKindOvnKubernetesNetwork(ctx, k8sClientset, zoneName)
+}
+
+/*
+
+openshift non-ic: in this case there will get the "app=ovnkube-node" and check for ovnkube-db service,
+if present we will the default Openshift db path
+
+openshift ic with one node per zone: if above service is not present we will return default Openshift socket path
+*/
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go:212]:
```suggestion
OpenShift non-ic: Identify pods labeled as "app=ovnkube-node" along with a corresponding service named ovnkube-db. When we locate such pods and services, we use the defaultOpenshiftOVNNBDB path.

OpenShift with OVN-IC and one node per zone: If the ovnkube-db service does not exist, we use the defaultOVNOpenshiftUnixSocket path.
*/
```

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 11]
```diff
@@ -186,45 +188,85 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+
+func discoverOpenshiftOvnKubernetesNetwork(ctx context.Context, k8sClientSet clientset.Interface) (string, error) {
+	ovnPod, err := FindPod(ctx, k8sClientSet, "app=ovnkube-node")
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go:215]: At a couple of places, we are using "app=ovnkube-node". This can be replaced with a constant.

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 12]
```diff
@@ -293,3 +338,22 @@ func FindPod(ctx context.Context, k8sClientset clientset.Interface, labelSelecto
...
+func FindOpenshiftNetwork(ctx context.Context, dynamicClient dynamic.Interface) (*unstructured.Unstructured, error) {
+	networkClient := dynamicClient.Resource(
+		schema.GroupVersionResource{
+			Group:    "config.openshift.io",
+			Version:  "v1",
+			Resource: "networks",
+		},
+	)
+
+	networks, err := networkClient.Get(ctx, "cluster", metav1.GetOptions{})
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go:352]: Just to confirm, there is no need to add any additional RBAC right?

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 13]
```diff
@@ -186,45 +188,85 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+
+/*
+   The discovery method is different for each kind of deployment.
+        kind non-ic: Get the db pod with label name=ovnkube-db, if present will get the protocol and other details from it
+
+        kind ic with multiple node per zone: we parse every endpoint in the namespace ovn uses and find the one that has
+        same zone as the node in which route-agent runs. To get the ovn namespace we use pods running on app=ovnkube-node.
+
+        kind ic with one node per zone: we will have no endpoints matching hence we will return default kind socket path
+*/
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go:236]:
```suggestion
   The discovery method varies based on the deployment type.
   
        kind non-ic: Search for the db pod with label "name=ovnkube-db" and if its present, use the protocol and other details from the pod.

        kind ic with multiple nodes per zone: Parse every endpoint in the namespace where OVN pods are running and find the one that has
        same zone as the node in which route-agent runs. To get the ovn namespace we use the namespace of the pods with label app=ovnkube-node.

        kind ic with one node per zone: we will have no endpoints matching hence we will return default kind socket path
*/
```

File: pkg/routeagent_driver/handlers/ovn/connection.go [hunk 14]
```diff
@@ -186,45 +188,85 @@ func getTLSConfig(k8sClientset clientset.Interface) (*tls.Config, error) {
...
+	}
 
 	if ovnDBPod != nil {
-		nbdbAddress, err = discoverOvnDBClusterNetwork(ctx, k8sClientset, ovnDBPod)
-	} else {
-		nbdbAddress, err = discoverOvnNodeClusterNetwork(ctx, k8sClientset, zoneName)
+		return discoverKindOvnDBClusterNetwork(ctx, ovnDBPod, k8sClientSet)
 	}
 
+	ovnPod, err := FindPod(ctx, k8sClientSet, "app=ovnkube-node")
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/connection.go:248]: Looks like you are using ovnPod just for the namespace. Can we use the namespace of ovnDBPod? or do you think they can be deployed in different namespaces?

**Review by sridhargaddam — COMMENTED** [review]
Thanks for refactoring the code @aswinsuryan 

If you happen to re-spin, please address the review comments.

**Comment by sridhargaddam** [comment]
Verified the PR manually in an OCP 4.13.10 cluster and confirm that CrashloopBackoff Error is no longer seen.

**Review by sridhargaddam — APPROVED** [review]
As discused on slack, please address the review comments in a follow up PR. 

https://kubernetes.slack.com/archives/C010RJV694M/p1694419770879479?thread_ts=1694415527.515619&cid=C010RJV694M

**Review by yboaron — APPROVED** [review]

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 12 above)
Comment (yboaron) [reply pkg/routeagent_driver/handlers/ovn/connection.go:352]: It is 
https://github.com/submariner-io/submariner-operator/blob/devel/config/rbac/submariner-route-agent/cluster_role.yaml#L51

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 14 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:248]: This if for the case where we are not able to find a db pod.

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 13 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:236]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 11 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:215]: Done

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 10 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:212]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 9 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:253]: Done.

File: pkg/routeagent_driver/handlers/ovn/connection.go (hunk 8 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/ovn/connection.go:222]: non-ic deployment identification is not same for kind and Openshift. So cannot have common for both.
