### PR TITLE
Stop adding the endpoint PrivateIP/32 to the subnet list in libreswan

### LINKED ISSUE #1253: libreswan fails when non standard ports are used, and Private IPS are used between two endpoints.
**What happened**:

the clusters can't connect to each other and we can see on the submariner-gateway logs:

```
I0412 13:36:37.140531       1 libreswan.go:368] Executing whack with args: [--psk --encrypt --name submariner-cable-kind2-172-18-0-9-0-0 --id 172.18.0.10 --host 172.18.0.10 --client 172.18.0.10/32 --ikeport 4511 --to --id 172.18.0.9 --host 172.18.0.9 --client 172.18.0.9/32 --ikeport 4502]
002 adding UDP interface eth0 172.18.0.10:4511
002 "submariner-cable-kind2-172-18-0-9-0-0": added IKEv2 connection
003 "submariner-cable-kind2-172-18-0-9-0-0": cannot install route: peer is within its client
025 "submariner-cable-kind2-172-18-0-9-0-0": could not route
```

**What you expected to happen**:

Connection can be created.

**How to reproduce it (as minimally and precisely as possible)**:

kubectl label $gw1 gateway.submariner.io/udp-port=4511 --kubeconfig config-cluster-1
kubectl delete pod -l app=submariner-gateway -n submariner-operator  --kubeconfig config-cluster-1

kubectl label $gw2 gateway.submariner.io/udp-port=4502 --kubeconfig config-cluster-2
kubectl delete pod -l app=submariner-gateway -n submariner-operator  --kubeconfig config-cluster-2

https://bugzilla.redhat.com/show_bug.cgi?id=1934058

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #1262: NAT discovery will incorrently say no-nat and PrivateIP once tunnels are established on the dataplane
**What happened**:

Once there's a established tunnel between endpoints, any new attempt to nat-discover will result in discovery the PrivateIP as reachable, because we add such IP as part of the subnets to be routed since 2cb35578739f64de74f4395a4eb3c130c2df7aed.

```

I0414 10:44:53.802917       1 request_send.go:115] Sending request - REQUEST_NUMBER: 0x7801fef43746a06c, SENDER: "submariner-cable-microk8s-cluster1-192-168-1-12", RECEIVER: "submariner-cable-majopela-b--1618393797-10-0-81-153", USING_SRC: 192.168.1.12:4100, USING_DST: 10.0.81.153:4490
I0414 10:44:53.803125       1 request_send.go:115] Sending request - REQUEST_NUMBER: 0x7801fef43746a06d, SENDER: "submariner-cable-microk8s-cluster1-192-168-1-12", RECEIVER: "submariner-cable-majopela-b--1618393797-10-0-81-153", USING_SRC: 192.168.1.12:4100, USING_DST: 3.142.235.237:4490
I0414 10:44:53.922319       1 response_handle.go:31] Received response from 3.142.235.237 - REQUEST_NUMBER: 0x7801fef43746a06d, RESPONSE: SRC_MODIFIED, SENDER: "submariner-cable-majopela-b--1618393797-10-0-81-153", RECEIVER: "submariner-cable-microk8s-cluster1-192-168-1-12"
I0414 10:44:53.922377       1 remote_endpoint.go:134] selected public IP "3.142.235.237" for endpoint "submariner-cable-majopela-b--1618393797-10-0-81-153"
I0414 10:44:53.922435       1 cableengine.go:154] Cable "submariner-cable-majopela-b--1618393797-10-0-81-153" is already installed - not installing again
I0414 10:44:53.928066       1 response_handle.go:31] Received response from 10.0.81.153 - REQUEST_NUMBER: 0x7801fef43746a06c, RESPONSE: OK, SENDER: "submariner-cable-majopela-b--1618393797-10-0-81-153", RECEIVER: "submariner-cable-microk8s-cluster1-192-168-1-12"
I0414 10:44:53.928128       1 remote_endpoint.go:166] updated to private IP "10.0.81.153" for endpoint "submariner-cable-majopela-b--1618393797-10-0-81-153"
```
note the **I0414 10:44:53.928128       1 remote_endpoint.go:166] updated to private IP "10.0.81.153" for endpoint "submariner-cable-majopela-b--1618393797-10-0-81-153"**

**What you expected to happen**:

The PrivateIP is not reachable outside of the tunnel, so should not be detected as reachable.

**How to reproduce it (as minimally and precisely as possible)**:

Enable nat discovery between NAT endpoints,  restart submariner-gateway on one of the sides.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by mangelajo**
This was initially introduced in this commit 2cb35578739f64de74f4395a4eb3c130c2df7aed
but it's not necessary anymore and has been verified with NAT and no-NAT
environments.

Fixes-Issue: #1253
Fixes-Issue: #1262

Although this reverts  2cb35578739f64de74f4395a4eb3c130c2df7aed functionality

I have manually verified that it works with NAT environments & that it passes all dataplane E2E:
```
[majopela@bluehat subm-demo]$ subctl show connections
Showing information for cluster "majopela-b--1618393797":
GATEWAY         CLUSTER                 REMOTE IP      NAT  CABLE DRIVER  SUBNETS                       STATUS     RTT avg.
ubuntu20        microk8s-cluster1       46.6.1.38      yes  libreswan     10.152.183.0/24, 10.1.0.0/16  connected  124.672361ms
ip-10-0-94-150  majopela-a--1618393797  3.138.186.212  yes  libreswan     172.30.0.0/16, 10.128.0.0/14  connected  303.063µs
```

```
•SSSSSS
Ran 11 of 36 Specs in 141.588 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 25 Skipped
```

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

### CODE REVIEW

File: pkg/cable/libreswan/libreswan.go [hunk 1]
```diff
@@ -246,11 +246,10 @@ func (i *libreswan) GetConnections() ([]subv1.Connection, error) {
 }
 
 func extractSubnets(endpoint subv1.EndpointSpec) []string {
-	// Subnets
-	subnets := []string{endpoint.PrivateIP + "/32"}
+	subnets := []string{}
```
Comment (tpantelis) [inline pkg/cable/libreswan/libreswan.go]:
```suggestion
	subnets := make([]string, 0, len(endpoint.Subnets))
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/cable/libreswan/libreswan.go (hunk 1 above)
Comment (mangelajo) [reply pkg/cable/libreswan/libreswan.go]: what's the benefit of that, not having to grow the slice later I guess?

Comment (mangelajo) [reply pkg/cable/libreswan/libreswan.go]: https://medium.com/vendasta/golang-the-time-complexity-of-append-2177dcfb6bad#:~:text=In%20Go%2C%20append(slice%2C,cost%20is%20O(N).

Comment (mangelajo) [reply pkg/cable/libreswan/libreswan.go]: nice. I'll let E2E run, and I'll update the patch.

**Review by tpantelis — APPROVED** [review]

**Review by SteveMattar — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]
