### PR TITLE
Use the CNI interface IP as src ip for g/w hostnetworking traffic

### LINKED ISSUE #1430: Globalnet test fail for vxlan cable driver
**What happened**:
------------------------------
STEP: Creating namespace objects with basename "dataplane-gn-conn-nd"
STEP: Generated namespace "e2e-tests-dataplane-gn-conn-nd-xn8rh" in cluster "cluster2" to execute the tests in
STEP: Creating namespace "e2e-tests-dataplane-gn-conn-nd-xn8rh" in cluster "cluster1"
STEP: Creating a listener pod in cluster "cluster1", which will wait for a handshake over TCP
STEP: Pointing a ClusterIP service to the listener pod in cluster "cluster1"
STEP: Creating a connector pod in cluster "cluster2", which will attempt the specific UUID handshake over TCP
Jun 21 18:25:26.827: INFO: ExecWithOptions {Command:[sh -c for j in $(seq 50); do echo [dataplane] connector says 236bf263-853c-4fdf-8212-2d6f7095f694; done | for i in $(seq 7); do if nc -v 169.254.1.252 1234 -w 18; then break; else sleep 9; fi; done] Namespace:e2e-tests-dataplane-gn-conn-nd-xn8rh PodName:customxl7k4 ContainerName:connector-pod Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
STEP: Waiting for the listener pod "tcp-check-listener5m4hm" on node "cluster1-worker" to exit, returning what listener sent
Jun 21 18:25:36.955: INFO: Pod "tcp-check-listener5m4hm" output:
listening on 0.0.0.0:1234 ...
connect to 10.0.0.9:1234 from 169.254.2.253:46631 (169.254.2.253:46631)
[dataplane] connector says 236bf263-853c-4fdf-8212-2d6f7095f694
STEP: Verifying that the listener got the connector's data and the connector got the listener's data
STEP: Verifying the output of listener pod which must contain the globalIP assigned to the Cluster
STEP: Deleting service "test-svc-tcp-check-listener" on "cluster1"
STEP: Deleting namespace "e2e-tests-dataplane-gn-conn-nd-xn8rh" on cluster "cluster2"
STEP: Deleting namespace "e2e-tests-dataplane-gn-conn-nd-xn8rh" on cluster "cluster1"
[dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod with HostNetworking connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway 
  should have sent the expected data from the pod to the other pod
  /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_gn_pod_connectivity.go:33
STEP: Creating namespace objects with basename "dataplane-gn-conn-nd"
STEP: Generated namespace "e2e-tests-dataplane-gn-conn-nd-hwl6h" in cluster "cluster2" to execute the tests in
STEP: Creating namespace "e2e-tests-dataplane-gn-conn-nd-hwl6h" in cluster "cluster1"
STEP: Creating a listener pod in cluster "cluster1", which will wait for a handshake over TCP
STEP: Pointing a ClusterIP service to the listener pod in cluster "cluster1"
STEP: Creating a connector pod in cluster "cluster2", which will attempt the specific UUID handshake over TCP
Jun 21 18:25:53.382: INFO: ExecWithOptions {Command:[sh -c for j in $(seq 50); do echo [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0; done | for i in $(seq 7); do if nc -v 169.254.1.252 1234 -w 18; then break; else sleep 9; fi; done] Namespace:e2e-tests-dataplane-gn-conn-nd-hwl6h PodName:customxg8gr ContainerName:connector-pod Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
STEP: Waiting for the listener pod "tcp-check-listener84m4l" on node "cluster1-control-plane" to exit, returning what listener sent
Jun 21 18:25:58.535: INFO: Pod "tcp-check-listener84m4l" output:
listening on 0.0.0.0:1234 ...
connect to 10.0.192.1:1234 from 10.0.0.1:42905 (10.0.0.1:42905)
[dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
STEP: Verifying that the listener got the connector's data and the connector got the listener's data
STEP: Verifying the output of listener pod which must contain the globalIP assigned to the Cluster
STEP: Deleting namespace "e2e-tests-dataplane-gn-conn-nd-hwl6h" on cluster "cluster2"
STEP: Deleting namespace "e2e-tests-dataplane-gn-conn-nd-hwl6h" on cluster "cluster1"
• Failure [21.428 seconds]
[dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery
/go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_gn_pod_connectivity.go:27
  when a pod with HostNetworking connects via TCP to the globalIP of a remote service
  /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_gn_pod_connectivity.go:74
    when the pod is on a gateway and the remote service is not on a gateway
    /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_gn_pod_connectivity.go:84
      should have sent the expected data from the pod to the other pod [It]
      /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_gn_pod_connectivity.go:33
      Expected
          <string>: listening on 0.0.0.0:1234 ...
          connect to 10.0.192.1:1234 from 10.0.0.1:42905 (10.0.0.1:42905)
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
          [dataplane] connector says b29436d8-92ea-4739-b7e1-9ae3989a90f0
      to contain substring
          <string>: 169.254.2.253

**What you expected to happen**:
Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.10.m2
- Kubernetes version (use `kubectl version`):
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #1486: e2e is failing with VXLAN cable driver in OpenShift
**What happened**:

[dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway 
  should have sent the expected data from the pod to the other pod
  github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:32
STEP: Creating namespace objects with basename "dataplane-conn-nd"
STEP: Generated namespace "e2e-tests-dataplane-conn-nd-h2578" in cluster "asuryana-pre-release-2" to execute the tests in
STEP: Creating namespace "e2e-tests-dataplane-conn-nd-h2578" in cluster "asuryana-pre-release-1"
STEP: Creating a listener pod in cluster "asuryana-pre-release-1", which will wait for a handshake over TCP
Jul 15 17:16:37.334: INFO: Will send traffic to IP: 10.150.0.52
STEP: Creating a connector pod in cluster "asuryana-pre-release-2", which will attempt the specific UUID handshake over TCP
STEP: Waiting for the connector pod "tcp-check-podz88bn" on node "" to exit, returning what connector sent
Jul 15 17:19:43.375: INFO: Pod "tcp-check-podz88bn" output:
nc: 10.150.0.52 (10.150.0.52:1234): Operation timed out
nc: 10.150.0.52 (10.150.0.52:1234): Operation timed out

STEP: Waiting for the listener pod "tcp-check-listenersqgmk" on node "ip-10-0-163-182.us-east-2.compute.internal" to exit, returning what listener sent
Jul 15 17:19:44.421: INFO: Pod "tcp-check-listenersqgmk" output:
listening on 0.0.0.0:1234 ...
nc: timeout

Jul 15 17:19:44.421: INFO: Connector pod has IP: 10.0.26.195
STEP: Deleting namespace "e2e-tests-dataplane-conn-nd-h2578" on cluster "asuryana-pre-release-2"
STEP: Deleting namespace "e2e-tests-dataplane-conn-nd-h2578" on cluster "asuryana-pre-release-1"

• Failure [194.846 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:26
  when a pod with HostNetworking connects via TCP to a remote pod
  github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:95
    when the pod is on a gateway and the remote pod is not on a gateway
    github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:105
      should have sent the expected data from the pod to the other pod [It]
      github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:32

      Expected
          <int32>: 1
      to equal
          <int32>: 0

      github.com/submariner-io/shipyard@v0.10.0-rc0/test/e2e/framework/network_pods.go:185

**What you expected to happen**:
All tests should pass, but one failed.
**How to reproduce it (as minimally and precisely as possible)**:
Run e2e in a AWS VXLAN setup.
**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): v0.10.0-rc0
- Kubernetes version (use `kubectl version`): 1.21
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by aswinsuryan**
For hostnetworking traffic from g/w node , use the CNI interface ip
as the source IP instead of vxlan-tunnel interface ip.

Fixes: #1430
Fixes: #1486

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

### CODE REVIEW

File: pkg/cable/vxlan/vxlan.go [hunk 1]
```diff
@@ -304,7 +307,14 @@ func (v *vxlan) ConnectToEndpoint(endpointInfo *natdiscovery.NATEndpointInfo) (s
 		return endpointInfo.UseIP, fmt.Errorf("failed to add remoteIP %q to the forwarding database", remoteIP)
 	}
 
-	err = v.vxlanIface.AddRoute(allowedIPs, remoteVtepIP, v.vxlanIface.vtepIP)
+	cniIface, err := cni.Discover(v.localCluster.Spec.ClusterCIDR[0])
+
+	if err != nil {
+		return endpointInfo.UseIP, fmt.Errorf("failed to get the CNI interface IP for cluster CIDR %q",
```
Comment (sridhargaddam) [inline pkg/cable/vxlan/vxlan.go]: Recently we noticed some network-plugins not creating CNI interfaces (with an IP that belongs to the PodCIDR) on the nodes. 

In such situations is it possible to log a WARNING while continuing to support the inter-cluster traffic without the host-network support?

**Review by sridhargaddam — COMMENTED** [review]
Thanks for the PR @aswinsuryan

File: pkg/cable/vxlan/vxlan.go (hunk 1 above)
Comment (aswinsuryan) [reply pkg/cable/vxlan/vxlan.go]: Now using vxlan interface ip , if CNI interface ip does not exist.

File: pkg/cable/vxlan/vxlan.go [hunk 2]
```diff
@@ -304,7 +307,17 @@ func (v *vxlan) ConnectToEndpoint(endpointInfo *natdiscovery.NATEndpointInfo) (s
...
 
-	err = v.vxlanIface.AddRoute(allowedIPs, remoteVtepIP, v.vxlanIface.vtepIP)
+	cniIface, err := cni.Discover(v.localCluster.Spec.ClusterCIDR[0])
+	var ipAddress net.IP
+	if err == nil {
+		ipAddress = net.ParseIP(cniIface.IPAddress)
+	} else {
+		klog.Errorf("failed to get the CNI interface IP for cluster CIDR %q, hence using "+
+			"the vxlan interface IP %q", v.localCluster.Spec.ClusterCIDR[0], v.vxlanIface.vtepIP)
+		ipAddress = v.vxlanIface.vtepIP
```
Comment (sridhargaddam) [inline pkg/cable/vxlan/vxlan.go]: Normally we don't program any routing rules for the VxLAN CIDR. So if we use vxlanIface.vtepIP here, is it working? It's possible that it might work because we are talking about Gateway node to Gateway node where the sm-tunnel interface exists with that IPAddress. But can you please verify this once by modifying the code and confirm that? Thanks.

Comment (aswinsuryan) [reply pkg/cable/vxlan/vxlan.go]: it was using vxlanIface.vtepIP before this PR . It do fail for some use cases like host-networking traffic from g/w node to a pod not g/w.

Comment (aswinsuryan) [reply pkg/cable/vxlan/vxlan.go]: Now using not src ip for the route if CNI interface Ip is missing.

File: pkg/cable/vxlan/vxlan.go [hunk 3]
```diff
@@ -304,7 +307,17 @@ func (v *vxlan) ConnectToEndpoint(endpointInfo *natdiscovery.NATEndpointInfo) (s
 		return endpointInfo.UseIP, fmt.Errorf("failed to add remoteIP %q to the forwarding database", remoteIP)
 	}
 
-	err = v.vxlanIface.AddRoute(allowedIPs, remoteVtepIP, v.vxlanIface.vtepIP)
+	cniIface, err := cni.Discover(v.localCluster.Spec.ClusterCIDR[0])
+	var ipAddress net.IP
+	if err == nil {
+		ipAddress = net.ParseIP(cniIface.IPAddress)
+	} else {
+		klog.Errorf("failed to get the CNI interface IP for cluster CIDR %q, hence not using a source IP for the route",
```
Comment (sridhargaddam) [inline pkg/cable/vxlan/vxlan.go]:
```suggestion
		klog.Errorf("Failed to get the CNI interface IP for cluster CIDR %q, hence not using a source IP for the route",
```

**Review by sridhargaddam — APPROVED** [review]
Thanks for addressing the comments @aswinsuryan

**Comment by sridhargaddam** [comment]
@mangelajo can you pls take a look at this PR?

**Review by tpantelis — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]
