### PR TITLE
Remove globalIP annotation from node as part of uninstall operation

### LINKED ISSUE #1780: Remove globalIP annotation from node as part of uninstall operation
What happened:
Globalnet adds a globalIP annotation to the Gateway node which is used as healthcheck-ip.
Ideally this annotation should be removed as part of `subctl uninstall ....` operation, otherwise it could create issues during re-deployment.

How to reproduce it (as minimally and precisely as possible):
Check nodes annotations on cluster2
Run Submariner deployment

bin/subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --globalnet
bin/subctl join --kubeconfig output/kubeconfigs/kind-config-cluster1 broker-info.subm --clusterid cluster1 --natt=false
bin/subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 broker-info.subm --clusterid cluster2 --natt=false
Uninstall Submariner from cluster2

bin/subctl uninstall --kubeconfig output/kubeconfigs/kind-config-cluster2
Check node annotations on cluster2 gateway node

Environment:
Kind

### PR DESCRIPTION
**Pull request by sridhargaddam**
Fixes: https://github.com/submariner-io/submariner/issues/1780
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

File: pkg/globalnet/controllers/uninstall.go [hunk 1]
```diff
@@ -176,3 +180,41 @@ func deleteAllGlobalIngressIPObjs(smClientSet *versioned.Clientset) {
...
+	retryErr := retry.RetryOnConflict(retry.DefaultRetry, func() error {
+		node, err := k8sClientSet.CoreV1().Nodes().Get(context.TODO(), nodeName, metav1.GetOptions{})
+		if err != nil {
+			return errors.Wrapf(err, "unable to get node info for node %q", nodeName)
+		}
+
+		annotations := node.GetAnnotations()
+		if annotations == nil {
+			annotations = map[string]string{}
+		}
```
Comment (tpantelis) [inline pkg/globalnet/controllers/uninstall.go]:
```suggestion
		annotations := node.GetAnnotations()
		if annotations == nil || annotations[constants.SmGlobalIP] == "" {
			return nil
		}
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Comment by sridhargaddam** [comment]
Thanks for reviewing @tpantelis. The PR should be squashed before merging.

**Review by tpantelis — APPROVED** [review]

**Review by aswinsuryan — APPROVED** [review]
