### PR TITLE
Fix race condition in ovn routeagent handler

### LINKED ISSUE #2004: Race condition in ovn  routeagent handler
**What happened**:
The ovn routeagent could endup with missing flows if delete event come after a create  event for a cluster in case where g/w switch from one to another for a cluster. This would lead to broken connectivity due to missing flows.

The issue is discussed in https://github.com/submariner-io/submariner/pull/1989/

**What you expected to happen**:
Delete should be processed only if the endpoint is older than the last create event.

**How to reproduce it (as minimally and precisely as possible)**:
Trying g/w failover multiple times

**Anything else we need to know?**:

**Environment**:kind
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by aswinsuryan**
Fixes: #2004
Signed-off-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

File: pkg/routeagent_driver/handlers/ovn/handler.go [hunk 1]
```diff
@@ -169,6 +181,16 @@ func (ovn *Handler) RemoteEndpointUpdated(endpoint *submV1.Endpoint) error {
...
 
+	lastProcessedTime, ok := ovn.remoteEndpointTimeStamp[endpoint.Spec.ClusterID]
+
+	if ok && lastProcessedTime.After(endpoint.CreationTimestamp.Time) {
+		logger.Infof("Ignoring deleted remote %#v since a later endpoint was already"+
+			"processed", endpoint)
+		return nil
+	}
+
+	delete(ovn.remoteEndpointTimeStamp, endpoint.Spec.ClusterID)
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/ovn/handler.go]: Should this be in `RemoteEndpointRemoved`?

File: pkg/routeagent_driver/handlers/ovn/handler.go [hunk 2]
```diff
@@ -139,6 +141,14 @@ func (ovn *Handler) RemoteEndpointCreated(endpoint *submV1.Endpoint) error {
 	ovn.mutex.Lock()
 	defer ovn.mutex.Unlock()
 
+	lastProcessedTime, ok := ovn.remoteEndpointTimeStamp[endpoint.Spec.ClusterID]
+
+	if ok && lastProcessedTime.After(endpoint.CreationTimestamp.Time) {
+		logger.Infof("Ignoring new remote %#v since a later endpoint was already"+
+			"processed", endpoint)
+		return nil
+	}
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/ovn/handler.go]: We already have a `remoteEndpoints` map which stores the entire struct - can't we use that instead of introducing a new map that just stores the time stamp? @sridhargaddam

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/routeagent_driver/handlers/ovn/handler.go [hunk 3]
```diff
@@ -169,6 +181,16 @@ func (ovn *Handler) RemoteEndpointUpdated(endpoint *submV1.Endpoint) error {
...
+	lastProcessedTime, ok := ovn.remoteEndpointTimeStamp[endpoint.Spec.ClusterID]
+
+	if ok && lastProcessedTime.After(endpoint.CreationTimestamp.Time) {
+		logger.Infof("Ignoring deleted remote %#v since a later endpoint was already"+
+			"processed", endpoint)
+		return nil
+	}
+
+	delete(ovn.remoteEndpointTimeStamp, endpoint.Spec.ClusterID)
+
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/ovn/handler.go]: This is the update handler. This code should go in `RemoteEndpointRemoved` API

**Review by sridhargaddam — CHANGES_REQUESTED** [review]

**Review by tpantelis — APPROVED** [review]

File: pkg/routeagent_driver/handlers/ovn/handler.go [hunk 4]
```diff
@@ -139,6 +139,14 @@ func (ovn *Handler) RemoteEndpointCreated(endpoint *submV1.Endpoint) error {
 	ovn.mutex.Lock()
 	defer ovn.mutex.Unlock()
 
+	existingEndPoint, ok := ovn.remoteEndpoints[endpoint.Spec.ClusterID]
+
+	if ok && existingEndPoint.CreationTimestamp.After(endpoint.CreationTimestamp.Time) {
+		logger.Infof("Ignoring new remote %#v since a later endpoint was already"+
+			"processed", endpoint)
```
Comment (skitt) [inline pkg/routeagent_driver/handlers/ovn/handler.go:146]:
```suggestion
		logger.Infof("Ignoring new remote %#v since a later endpoint was already "+
			"processed", endpoint)
```

File: pkg/routeagent_driver/handlers/ovn/handler.go [hunk 5]
```diff
@@ -187,6 +195,14 @@ func (ovn *Handler) RemoteEndpointRemoved(endpoint *submV1.Endpoint) error {
 	ovn.mutex.Lock()
 	defer ovn.mutex.Unlock()
 
+	existingEndPoint, ok := ovn.remoteEndpoints[endpoint.Spec.ClusterID]
+
+	if ok && existingEndPoint.CreationTimestamp.After(endpoint.CreationTimestamp.Time) {
+		logger.Infof("Ignoring deleted remote %#v since a later endpoint was already"+
+			"processed", endpoint)
```
Comment (skitt) [inline pkg/routeagent_driver/handlers/ovn/handler.go:202]:
```suggestion
		logger.Infof("Ignoring deleted remote %#v since a later endpoint was already "+
			"processed", endpoint)
```

**Review by skitt — COMMENTED** [review]
If you get a chance, this is missing spaces in the log messages.

**Review by sridhargaddam — APPROVED** [review]
