### PR TITLE
Ignore endpoint events if processed already.

### LINKED ISSUE #1544: Gateway migration in one cluster is causing failures in remote cluster
**What happened**:
In a two-cluster setup (perf1 and perf2), install Submariner (with NAT disabled) to connect both the clusters and ensure that connections are successfully established. In such a setup, when the active gateway migrates on the Perf1 cluster, the routes in table 150 on the Active Gateway node of Perf2 are accidentally deleted. Because of this, pinger (aka Healthcheck) which runs on Perf2 gateway is unable to reach Perf1 health-check IP. Along with this, Hostnetworking to remoteCluster from Perf2 is broken.

**What you expected to happen**:
When the active Gateway migrates, the HostNetworking use-cases should continue to work.

A temporary work-around is to restart the route-agent running on the active Gateway node of the Perf2 cluster.

**Environment**:
Submariner version:	v0.9
Kubernetes Server version: v1.21.1+9807387
CNI: OpenShiftSDN on VmWare Clusters

Logs from route-agent running on the Active Gateway node of Perf2 cluster are attached:
[api-perf2-chris-ocs-ninja_6443_submariner-routeagent-xzx8f.log](https://github.com/submariner-io/submariner/files/7096459/api-perf2-chris-ocs-ninja_6443_submariner-routeagent-xzx8f.log)

### PR DESCRIPTION
**Pull request by aswinsuryan**
In deployments, if we delete submariner-gateway machineset and then
later delete the submariner namespace in a cluster. It would lead
to a stale endpoint in other clusters. Now if we create a machineset
and join the cluster again, the old endpoint gets cleared. But the old
endpoint delete event comes after the new endpoint is created and the
host network routing rules gets deleted.

With this fix, a delete event will be ignored if it has timestamp older
than the current endpoint.

Fixes: #1544

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

### CODE REVIEW

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 1]
```diff
@@ -101,6 +101,15 @@ func (kp *SyncHandler) RemoteEndpointCreated(endpoint *submV1.Endpoint) error {
 
 	kp.syncHandlerMutex.Lock()
 	defer kp.syncHandlerMutex.Unlock()
+
+	lastPorcessedTime, ok := kp.remoteEndpointTimeStamp[endpoint.Name]
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]:
```suggestion
	lastProcessedTime, ok := kp.remoteEndpointTimeStamp[endpoint.Name]
```

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 2]
```diff
@@ -101,6 +101,15 @@ func (kp *SyncHandler) RemoteEndpointCreated(endpoint *submV1.Endpoint) error {
...
+
+	if ok && lastPorcessedTime.After(endpoint.CreationTimestamp.Time) {
+		klog.Infof("Ingoring new remote %#v since a later endoint was already"+
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]: I'm not sure how noisy this could be but It seems this should be DEBUG or TRACE level.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 3]
```diff
@@ -129,6 +140,17 @@ func (kp *SyncHandler) RemoteEndpointUpdated(endpoint *submV1.Endpoint) error {
 func (kp *SyncHandler) RemoteEndpointRemoved(endpoint *submV1.Endpoint) error {
 	kp.syncHandlerMutex.Lock()
 	defer kp.syncHandlerMutex.Unlock()
+
+	lastPorcessedTime, ok := kp.remoteEndpointTimeStamp[endpoint.Name]
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]:
```suggestion
	lastProcessedTime, ok := kp.remoteEndpointTimeStamp[endpoint.Name]
```

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 4]
```diff
@@ -129,6 +140,17 @@ func (kp *SyncHandler) RemoteEndpointUpdated(endpoint *submV1.Endpoint) error {
...
+
+	if ok && lastPorcessedTime.After(endpoint.CreationTimestamp.Time) {
+		klog.Infof("Ingoring deleted remote %#v since a later endoint was already"+
```
Comment (tpantelis) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]: DEBUG or TRACE?

**Review by tpantelis — COMMENTED** [review]
Can you explain in the PR summary the proposed solution and how it fixes the issue?

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 5]
```diff
@@ -129,6 +140,17 @@ func (kp *SyncHandler) RemoteEndpointUpdated(endpoint *submV1.Endpoint) error {
...
+			"processed", endpoint)
+		return nil
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: The exact problem that we noticed in OCP deployment was that a stale/old endpoint event coming after an updated event. Here we are skipping the old one, but what about deleting any resources (like iptables, routes etc) which point to the old endpoint? Can you please point me where we will handle it with this change?

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 2 above)
Comment (sridhargaddam) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]: Ideally, these events should happen only during migration and if there is out-of-order events. So, I would guess it should be less noisy.

**Review by sridhargaddam — CHANGES_REQUESTED** [review]

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 5 above)
Comment (tpantelis) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: This code correlates the time stamp between endpoints with the same name. I'm curious what sequence of events can occur for endpoint(s) with the same name that would cause an issue? Can the exact scenario sequence that we're trying to solve be outlined in the PR?

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 5 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: Added more details to the commit message.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 3 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]: Done.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 2 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]: Ya it should happen only in corner conditions and should be good for us to know if it happens.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 4 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]: Retaining Info as mentioned above.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 5 above)
Comment (sridhargaddam) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: @aswinsuryan, thanks for the PR. I see that you are now skipping the endpoint processing if its arriving after the new endpoint. Can you please check that on the old gateway node, the following entries are removed. We are seeing this more often in OCP setup.

1. IP route table 150 entries
2. vx-submariner interface 
3. IP xfrm policy/state rules

**Review by sridhargaddam — COMMENTED** [review]
Thanks for the PR @aswinsuryan. I have one comment.

**Comment by sridhargaddam** [comment]
@aswinsuryan ping.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 5 above)
Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: @sridhargaddam This issue occurs when the old g/w node(machine set) is deleted and a new one is created. So in the remote cluster, the old one does not exist. In the local cluster, g/w node did not change, but it received a stale event. So we need to keep that rules.

Is  that what you meant to do?

**Comment by aswinsuryan** [comment]
> @aswinsuryan ping.
Replied in the comments.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go (hunk 5 above)
Comment (dfarrell07) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: > This issue occurs when the old g/w node(machine set) is deleted and a new one is created.

Is it possible to add tests for this scenario? I'm thinking of the [CII Silver](https://bestpractices.coreinfrastructure.org/en/criteria) requirement: 

> The project MUST add regression tests to an automated test suite for at least 50% of the bugs fixed within the last six months.

Comment (aswinsuryan) [reply pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go:153]: @dfarrell07 I am not sure if it can be done in kind,may be removing a worker node and adding it back help.

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 6]
```diff
@@ -135,6 +145,16 @@ func (kp *SyncHandler) RemoteEndpointRemoved(endpoint *submV1.Endpoint) error {
 	kp.syncHandlerMutex.Lock()
 	defer kp.syncHandlerMutex.Unlock()
 
+	lastProcessedTime, ok := kp.remoteEndpointTimeStamp[endpoint.ClusterName]
+
+	if ok && lastProcessedTime.After(endpoint.CreationTimestamp.Time) {
+		klog.Infof("Ignoring deleted remote %#v since a later endoint was already"+
+			"processed", endpoint)
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]:
```suggestion
		klog.Infof("Ignoring deleted remote %#v since a later endpoint was already"+
			"processed", endpoint)
```

File: pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go [hunk 7]
```diff
@@ -105,6 +105,14 @@ func (kp *SyncHandler) RemoteEndpointCreated(endpoint *submV1.Endpoint) error {
 	kp.syncHandlerMutex.Lock()
 	defer kp.syncHandlerMutex.Unlock()
 
+	lastProcessedTime, ok := kp.remoteEndpointTimeStamp[endpoint.ClusterName]
+
+	if ok && lastProcessedTime.After(endpoint.CreationTimestamp.Time) {
+		klog.Infof("Ignoring new remote %#v since a later endoint was already"+
```
Comment (sridhargaddam) [inline pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go]:
```suggestion
		klog.Infof("Ignoring new remote %#v since a later endpoint was already"+
```

**Review by sridhargaddam — COMMENTED** [review]
Thanks @aswinsuryan. Some minor nits

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]
